"use server";

import { revalidatePath } from "next/cache";

import { requireSession } from "@/lib/auth";
import { recordAudit } from "@/lib/audit";
import { UNITS } from "@/lib/pos/catalog";
import {
  billOf,
  businessDayOf,
  isTender,
  round3,
  type CartLine,
  type TenderId,
} from "@/lib/pos/counter";
import { getShopSettings } from "@/lib/pos/shop";
import { createAdminClient } from "@/utils/supabase/admin";

/**
 * Recording one sale.
 *
 * The register works the bill out on the tablet so a slow connection never
 * slows a queue down — but nothing the tablet computed is trusted here. The
 * browser sends item ids and quantities and nothing else; every price, tax rate
 * and unit is looked up again on this side, and the total is recomputed with
 * the same `billOf` the screen used. A crafted request can therefore buy things
 * at the wrong quantity, which is a stocktake problem, and never at the wrong
 * price, which would be a money problem.
 *
 * The write itself is `public.record_sale` — one security-definer function, one
 * transaction. It claims the counter's next receipt number and inserts the
 * sale, its lines and its tender together, because a number claimed against a
 * sale that then failed to insert is a hole in the shop's series that nobody
 * can account for.
 *
 * `saleId` is generated by the browser. A retry after a dropped connection
 * replays with the same id and gets the same receipt back rather than recording
 * the bill twice.
 */

export type SaleInput = {
  saleId: string;
  counterId: string;
  tender: TenderId;
  lines: { id: string; quantity: number }[];
};

export type SaleResult =
  | { ok: true; receiptNo: string; total: number }
  | { ok: false; error: string };

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export async function recordSale(input: SaleInput): Promise<SaleResult> {
  const session = await requireSession();

  if (!session.tenantId) {
    return { ok: false, error: "This login is not linked to a shop." };
  }

  if (!UUID.test(input.saleId) || !UUID.test(input.counterId)) {
    return { ok: false, error: "That sale is malformed. Start it again." };
  }

  if (!isTender(input.tender)) {
    return { ok: false, error: "That is not a payment method this counter takes." };
  }

  const wanted = input.lines ?? [];

  if (wanted.length === 0) {
    return { ok: false, error: "There is nothing on this bill." };
  }

  if (!wanted.every((line) => UUID.test(line.id))) {
    return { ok: false, error: "That sale is malformed. Start it again." };
  }

  const supabase = createAdminClient();

  // Re-priced from the catalog, not from the browser. This is the whole of the
  // trust boundary: the client chooses what and how many, the server decides
  // what it costs. A crafted request can therefore buy things at the wrong
  // quantity, which is a stocktake problem, and never at the wrong price.
  //
  // `is_active` is on the read for the same reason it is on the register's:
  // a tab left open since an item was withdrawn must not be able to sell it.
  const { data: catalog } = await supabase
    .from("items")
    .select("id, name, name_urdu, unit, selling_price, tax_rate")
    .eq("tenant_id", session.tenantId)
    .eq("is_active", true)
    .in("id", [...new Set(wanted.map((line) => line.id))]);

  const priced = new Map((catalog ?? []).map((row) => [row.id, row]));
  const lines: CartLine[] = [];

  for (const line of wanted) {
    const item = priced.get(line.id);
    if (!item) {
      return { ok: false, error: "One of those items is no longer in the list." };
    }

    // 'kilo' is 0008's spelling, still valid in the column. One name here.
    const unit = (item.unit === "kilo" ? "kg" : item.unit) as CartLine["unit"];
    const fractional = UNITS.find((entry) => entry.id === unit)?.fractional ?? false;
    const quantity = round3(Number(line.quantity));

    if (!Number.isFinite(quantity) || quantity <= 0 || quantity > 99_999) {
      return {
        ok: false,
        error: `The quantity on ${item.name} is not a number we can sell.`,
      };
    }

    if (!fractional && !Number.isInteger(quantity)) {
      return { ok: false, error: `${item.name} is sold in whole ${unit}s.` };
    }

    lines.push({
      id: item.id,
      name: item.name,
      urdu: item.name_urdu ?? "",
      unit,
      quantity,
      price: Number(item.selling_price) || 0,
      taxRate: Number(item.tax_rate) || 0,
      fractional,
    });
  }

  // The counter, re-read rather than taken on trust: it has to be this shop's,
  // open, and willing to take the tender the sheet chose.
  const { data: counter } = await supabase
    .from("counters")
    .select("id, name, is_active, accepts_cash, accepts_card")
    .eq("id", input.counterId)
    .eq("tenant_id", session.tenantId)
    .maybeSingle();

  if (!counter || !counter.is_active) {
    return {
      ok: false,
      error: "This counter has been shut in Settings. Ask the owner to open it again.",
    };
  }

  const takes = input.tender === "cash" ? counter.accepts_cash : counter.accepts_card;
  if (!takes) {
    return { ok: false, error: `${counter.name} is not set up to take ${input.tender}.` };
  }

  const settings = await getShopSettings(session.tenantId);
  const bill = billOf(lines);

  const { data, error } = await supabase.rpc("record_sale", {
    p_tenant: session.tenantId,
    p_counter: counter.id,
    p_sale_id: input.saleId,
    // Stamped here, once, from the shop's own `day_ends_at`. Every report
    // afterwards reads the column instead of re-deriving a window from a
    // setting that can change.
    p_business_day: businessDayOf(new Date(), settings.timezone, settings.dayEndsAt),
    p_created_by: session.userId,
    p_subtotal: bill.subtotal,
    p_total: bill.total,
    p_tender: input.tender,
    p_lines: lines.map((line) => ({
      // The catalog row this line came off, so a report can group by item.
      // `name_snapshot` beside it is what the receipt was printed from, and it
      // is what survives the item being deleted.
      item_id: line.id,
      name: line.name,
      unit: line.unit,
      quantity: line.quantity,
      unit_price: line.price,
      line_total: Math.round(line.price * line.quantity * 100) / 100,
    })),
  });

  const receiptNo =
    data && typeof data === "object" && "receipt_number" in data
      ? String((data as { receipt_number: unknown }).receipt_number)
      : null;

  if (error || !receiptNo) {
    console.error("[register] record_sale failed", error);
    return {
      ok: false,
      error:
        "We could not record this sale. Check the connection and try again — or print it and take the money, and it will be missing from today's takings until it is re-entered.",
    };
  }

  const replayed =
    data && typeof data === "object" && "replayed" in data
      ? Boolean((data as { replayed: unknown }).replayed)
      : false;

  // A replay is the same sale arriving twice, not a second one. Auditing it
  // again would put two entries against one receipt and make the log lie about
  // how much was sold.
  if (!replayed) {
    await recordAudit(session, {
      action: "sale.recorded",
      subjectType: "sale",
      subjectId: input.saleId,
      after: {
        counter_id: counter.id,
        receipt_number: receiptNo,
        tender: input.tender,
        total: bill.total,
        lines: bill.lines,
      },
    });
  }

  // The day-end screen is the one that has to be right the moment a sale lands.
  revalidatePath("/app/sales");

  return { ok: true, receiptNo, total: bill.total };
}
