"use server";

import { revalidatePath } from "next/cache";

import { requireSession } from "@/lib/auth";
import { recordAudit } from "@/lib/audit";
import { getEntitlements } from "@/lib/entitlements";
import { UNITS } from "@/lib/pos/catalog";
import {
  billOf,
  businessDayOf,
  cartKey,
  discountOf,
  isTender,
  round2,
  round3,
  tender,
  type CartLine,
  type Discount,
  type TenderId,
  type TenderPart,
} from "@/lib/pos/counter";
import { writeVariant } from "@/lib/pos/variant";
import { getTillAccess } from "@/lib/pos/access";
import { getShopSettings } from "@/lib/pos/shop";
import { createAdminClient } from "@/utils/supabase/admin";

/**
 * Recording one sale.
 *
 * The register works the bill out on the tablet so a slow connection never
 * slows a queue down — but nothing the tablet computed is trusted here. The
 * browser sends item ids and quantities and nothing else; every price, tax rate
 * and unit is looked up again on this side, and the total is recomputed with
 * the same `billOf` the screen used. A crafted request can therefore buy things
 * at the wrong quantity, which is a stocktake problem, and never at the wrong
 * price, which would be a money problem.
 *
 * The write itself is `public.record_sale` — one security-definer function, one
 * transaction. It claims the counter's next receipt number and inserts the
 * sale, its lines and its tender together, because a number claimed against a
 * sale that then failed to insert is a hole in the shop's series that nobody
 * can account for.
 *
 * `saleId` is generated by the browser. A retry after a dropped connection
 * replays with the same id and gets the same receipt back rather than recording
 * the bill twice.
 */

export type SaleInput = {
  saleId: string;
  counterId: string;
  /**
   * How the customer settled it, in parts. One on the overwhelming majority of
   * bills; more when somebody puts two thousand on a card and hands over the
   * rest in notes, which is an ordinary Saturday and until `0032` could only be
   * recorded as one of the two.
   *
   * Change is already off these figures — `settleTenders` on the till takes it
   * out of the cash part, because recording the note a customer handed over
   * would overstate the drawer by exactly the change every time.
   */
  tenders: TenderPart[];
  /** What the browser asks for: a catalog id, which size or colour of it, and
   *  how many. Nothing about price — the server decides that, which is the
   *  whole of the trust boundary here. */
  lines: { id: string; variantId: string | null; quantity: number }[];
  /** Who the bill is for. Null is a walk-in, which is most bills. */
  customerId: string | null;
  /**
   * What the cashier agreed to take off, as they said it — per cent or rupees.
   * Resolved to rupees on this side against this session's own ceiling, never
   * against one the browser sent: the ceiling is the whole control, and a
   * client that could name it would not be limited by it.
   */
  discount?: Discount;
};

export type SaleResult =
  | { ok: true; receiptNo: string; total: number; discount: number }
  | { ok: false; error: string };

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export async function recordSale(input: SaleInput): Promise<SaleResult> {
  const session = await requireSession();

  if (!session.tenantId) {
    return { ok: false, error: "This login is not linked to a shop." };
  }

  /**
   * Is this shop still allowed to trade?
   *
   * The whole of what suspension means, and deliberately the *only* thing it
   * means. A suspended shop can still sign in, read every sale it has ever
   * made, export it, and close the drawer it opened this morning — what stops
   * is ringing up a new one. Holding a shop's own books hostage over an unpaid
   * invoice is indecent, it is the fastest way to earn a bad name in a bazaar,
   * and in a dispute about their own records it is the weaker position to be
   * standing in.
   *
   * Checked here rather than in `record_sale`, the same placement as the stock
   * and shift gates and for the same reason: a refusal in a Server Action is a
   * sentence somebody at a counter can act on, where a raise from a function is
   * a failed write with a Postgres message behind it.
   *
   * It fails open. A subscription that cannot be read is not evidence that
   * anybody stopped paying, and a shop with a customer at the counter must not
   * be shut by a network blip.
   */
  const entitlements = await getEntitlements(session.tenantId);

  if (entitlements && !entitlements.canOperate) {
    return {
      ok: false,
      error:
        "Billing is on hold for this shop, so the register cannot take a new sale. Everything already rung up is still here and still exports. Message us on WhatsApp and we will put it back on.",
    };
  }

  if (!UUID.test(input.saleId) || !UUID.test(input.counterId)) {
    return { ok: false, error: "That sale is malformed. Start it again." };
  }

  const tenders = (input.tenders ?? []).filter((part) => Number(part.amount) > 0);

  if (tenders.length === 0 || !tenders.every((part) => isTender(part.method))) {
    return { ok: false, error: "That is not a payment method this counter takes." };
  }

  const wanted = input.lines ?? [];

  if (wanted.length === 0) {
    return { ok: false, error: "There is nothing on this bill." };
  }

  if (!wanted.every((line) => UUID.test(line.id))) {
    return { ok: false, error: "That sale is malformed. Start it again." };
  }

  const supabase = createAdminClient();

  // Re-priced from the catalog, not from the browser. This is the whole of the
  // trust boundary: the client chooses what and how many, the server decides
  // what it costs. A crafted request can therefore buy things at the wrong
  // quantity, which is a stocktake problem, and never at the wrong price.
  //
  // `is_active` is on the read for the same reason it is on the register's:
  // a tab left open since an item was withdrawn must not be able to sell it.
  const { data: catalog } = await supabase
    .from("items")
    .select("id, name, name_urdu, unit, selling_price, tax_rate, stock")
    .eq("tenant_id", session.tenantId)
    .eq("is_active", true)
    .in("id", [...new Set(wanted.map((line) => line.id))]);

  const priced = new Map((catalog ?? []).map((row) => [row.id, row]));

  // The variants named, re-read on the same terms and for the same reason. A
  // variant carries its own stock and may carry its own price, so a bill that
  // took the item's numbers for a medium blue would be wrong twice over.
  const askedVariants = [
    ...new Set(wanted.map((line) => line.variantId).filter(Boolean)),
  ] as string[];

  const variants = new Map<
    string,
    { id: string; item_id: string; option_a: string; option_b: string | null;
      selling_price: number | string | null; quantity: number | string }
  >();

  if (askedVariants.length > 0) {
    const { data } = await supabase
      .from("item_variants")
      .select("id, item_id, option_a, option_b, selling_price, quantity")
      .eq("tenant_id", session.tenantId)
      .eq("is_active", true)
      .in("id", askedVariants);

    for (const row of data ?? []) variants.set(row.id as string, row);
  }

  const lines: CartLine[] = [];

  for (const line of wanted) {
    const item = priced.get(line.id);
    if (!item) {
      return { ok: false, error: "One of those items is no longer in the list." };
    }

    // 'kilo' is 0008's spelling, still valid in the column. One name here.
    const unit = (item.unit === "kilo" ? "kg" : item.unit) as CartLine["unit"];
    const fractional = UNITS.find((entry) => entry.id === unit)?.fractional ?? false;
    const quantity = round3(Number(line.quantity));

    if (!Number.isFinite(quantity) || quantity <= 0 || quantity > 99_999) {
      return {
        ok: false,
        error: `The quantity on ${item.name} is not a number we can sell.`,
      };
    }

    if (!fractional && !Number.isInteger(quantity)) {
      return { ok: false, error: `${item.name} is sold in whole ${unit}s.` };
    }

    // The variant, where the line named one. It has to belong to this item:
    // a crafted body pairing a cheap variant with a dear item is the one way
    // this endpoint could be made to sell at the wrong price.
    const variant = line.variantId ? variants.get(line.variantId) : undefined;

    if (line.variantId && (!variant || variant.item_id !== item.id)) {
      return {
        ok: false,
        error: `That size or colour of ${item.name} is no longer on the list.`,
      };
    }

    const label = variant ? writeVariant({
      optionA: variant.option_a,
      optionB: variant.option_b ?? "",
    }) : "";

    // The variant's own shelf where there is one — eight mediums and no larges
    // is not "eight in stock" for somebody asking for a large.
    const stock = variant
      ? Number(variant.quantity) || 0
      : Number(item.stock) || 0;

    const what = label ? `${item.name} (${label})` : item.name;

    // The shelf count is a gate, not a warning. The till refuses to put an
    // item at zero on a bill and refuses to step one past what is counted;
    // this is the same rule on the server, because a control the browser draws
    // is not a control nobody can call — and this read is the fresher of the
    // two, since the till's copy was loaded when the page was.
    //
    // It names the item and both numbers, because the fix is a stocktake on
    // Products & stock and the owner needs to know which row to open.
    if (quantity > stock) {
      return {
        ok: false,
        error:
          stock <= 0
            ? `${what} is out of stock, so it cannot be sold. Count it in on Products & stock first.`
            : `Flo counts ${stock} ${unit} of ${what} and this bill has ${quantity}. Lower it, or count the shelf in on Products & stock.`,
      };
    }

    lines.push({
      id: cartKey(item.id, variant?.id),
      itemId: item.id,
      variantId: variant?.id ?? null,
      variantLabel: label,
      name: item.name,
      urdu: item.name_urdu ?? "",
      unit,
      quantity,
      // The variant's own price where it has one, the item's otherwise — the
      // same rule `priceOf` states for the browser, resolved here because this
      // is the side that decides.
      price: variant
        ? Number(variant.selling_price ?? item.selling_price) || 0
        : Number(item.selling_price) || 0,
      taxRate: Number(item.tax_rate) || 0,
      fractional,
      stock,
    });
  }

  // The customer, re-read on the same terms as the counter below: this shop's,
  // and still on the list. `is_active` is on the read for the reason it is on
  // the catalog's — a tab left open since somebody was switched off must not be
  // able to bill against them.
  //
  // `record_sale` checks the tenant again inside the transaction. This one is
  // here so the refusal is a sentence a cashier can act on rather than a
  // failed write.
  let customerId: string | null = null;

  if (input.customerId) {
    if (!UUID.test(input.customerId)) {
      return { ok: false, error: "That sale is malformed. Start it again." };
    }

    const { data: customer } = await supabase
      .from("customers")
      .select("id")
      .eq("id", input.customerId)
      .eq("tenant_id", session.tenantId)
      .eq("is_active", true)
      .maybeSingle();

    if (!customer) {
      return {
        ok: false,
        error:
          "That customer is not on your list any more. Take them off the bill, or add them again on Customers.",
      };
    }

    customerId = customer.id;
  }

  // The counter, re-read rather than taken on trust: it has to be this shop's,
  // open, and willing to take the tender the sheet chose.
  const { data: counter } = await supabase
    .from("counters")
    .select("id, name, is_active, accepted_tenders")
    .eq("id", input.counterId)
    .eq("tenant_id", session.tenantId)
    .maybeSingle();

  if (!counter || !counter.is_active) {
    return {
      ok: false,
      error: "This counter has been shut in Settings. Ask the owner to open it again.",
    };
  }

  // Every part has to be something this till takes. `record_sale` checks it
  // again against the same column inside the transaction — this one is here so
  // the refusal is a sentence rather than a failed write.
  const accepted = (counter.accepted_tenders ?? []) as TenderId[];
  const refused = tenders.find((part) => !accepted.includes(part.method));

  if (refused) {
    return {
      ok: false,
      error: `${counter.name} is not set up to take ${tender(refused.method).label.toLowerCase()}.`,
    };
  }

  // No drawer, no sale. `record_sale` stamps whichever shift the counter is in
  // and a null `shift_id` used to be the ordinary case — it is now a sale that
  // belongs to nobody's count, which is the thing shifts exist to stop. Checked
  // here rather than in SQL for the reason the stock check above is: this is
  // where a refusal can be a sentence the cashier can act on.
  const { data: shift } = await supabase
    .from("shifts")
    .select("id")
    .eq("tenant_id", session.tenantId)
    .eq("counter_id", counter.id)
    .eq("status", "open")
    .maybeSingle();

  if (!shift) {
    return {
      ok: false,
      error: `No drawer is open on ${counter.name}. Open it at the top of the Register — a sale has to land in a till somebody has counted into.`,
    };
  }

  const settings = await getShopSettings(session.tenantId);

  // The discount, re-resolved here against the ceiling this session actually
  // has. `discountOf` is the same function the till used to draw the figure on
  // screen, so a cashier inside their limit sees the number they will be
  // charged — and one who edited the request gets it clamped rather than
  // refused, because a clamp is what the owner's ceiling means.
  const till = await getTillAccess(session);
  const asked = input.discount;

  if (asked && asked.value > 0 && !till.canDiscount) {
    return {
      ok: false,
      error: "You are not allowed to take anything off a bill. Ask the owner.",
    };
  }

  const gross = billOf(lines);
  const off =
    asked && till.canDiscount
      ? discountOf(gross.subtotal, asked, till.discountCeilingPct)
      : 0;

  const bill = billOf(lines, off);

  const { data, error } = await supabase.rpc("record_sale", {
    p_tenant: session.tenantId,
    p_counter: counter.id,
    p_sale_id: input.saleId,
    // Stamped here, once, from the shop's own `day_ends_at`. Every report
    // afterwards reads the column instead of re-deriving a window from a
    // setting that can change.
    p_business_day: businessDayOf(new Date(), settings.timezone, settings.dayEndsAt),
    p_created_by: session.userId,
    p_subtotal: bill.subtotal,
    p_total: bill.total,
    p_tenders: tenders.map((part) => ({
      method: part.method,
      amount: round2(Number(part.amount)),
      reference: (part.reference ?? "").trim().slice(0, 60) || null,
    })),
    p_discount: bill.discount,
    // The floor under the check above. `record_sale` raises rather than
    // clamps, so this being wrong is a failed sale and not a silent giveaway.
    p_ceiling_pct: till.discountCeilingPct,
    p_lines: lines.map((line) => ({
      // The catalog row this line came off, so a report can group by item.
      // `name_snapshot` beside it is what the receipt was printed from, and it
      // is what survives the item being deleted. `line.id` is the *cart* key
      // since `0031` and is deliberately not sent — the item and the variant
      // are two columns on `sale_lines`, and a composite key in one of them
      // would be a value nothing could join on.
      item_id: line.itemId,
      variant_id: line.variantId,
      name: line.variantLabel
        ? `${line.name} — ${line.variantLabel}`
        : line.name,
      unit: line.unit,
      quantity: line.quantity,
      unit_price: line.price,
      line_total: Math.round(line.price * line.quantity * 100) / 100,
    })),
    p_customer: customerId,
  });

  const receiptNo =
    data && typeof data === "object" && "receipt_number" in data
      ? String((data as { receipt_number: unknown }).receipt_number)
      : null;

  if (error || !receiptNo) {
    console.error("[register] record_sale failed", error);
    return {
      ok: false,
      error:
        "We could not record this sale. Check the connection and try again — or print it and take the money, and it will be missing from today's takings until it is re-entered.",
    };
  }

  const replayed =
    data && typeof data === "object" && "replayed" in data
      ? Boolean((data as { replayed: unknown }).replayed)
      : false;

  // A replay is the same sale arriving twice, not a second one. Auditing it
  // again would put two entries against one receipt and make the log lie about
  // how much was sold.
  if (!replayed) {
    await recordAudit(session, {
      action: "sale.recorded",
      subjectType: "sale",
      subjectId: input.saleId,
      after: {
        counter_id: counter.id,
        customer_id: customerId,
        receipt_number: receiptNo,
        // Every part by name. "Which bills were settled by JazzCash" is the
        // question a shop asks the day a wallet statement disagrees with the
        // takings, and it has to be answerable from the log as well as the row.
        tenders: tenders.map((part) => ({
          method: part.method,
          amount: round2(Number(part.amount)),
        })),
        total: bill.total,
        // Audited by name because it is the one figure on a bill the person
        // entering it benefits from getting wrong. A shop asking "who has been
        // giving money away" needs this answerable.
        discount: bill.discount,
        lines: bill.lines,
      },
    });
  }

  // The day-end screen is the one that has to be right the moment a sale lands.
  revalidatePath("/app/sales");

  return { ok: true, receiptNo, total: bill.total, discount: bill.discount };
}
