"use client";

import Image from "next/image";

import { Tilt } from "@/components/motion/tilt";

/**
 * The hero's product window: a real screenshot of the console, not a replica.
 *
 * The file under it is generated by `npm run shots`, which drives the running
 * app and photographs `/app`. That is the whole point — a hand-built mock of
 * your own product drifts the moment the product moves, and drifts silently,
 * because nothing links the two files. This cannot: it is the product.
 *
 * The dark console rather than the default light one, because the hero is dark
 * and the violet carries straight through from the page into the window. The
 * light counter is captured too (`dashboard-light.png`) for anywhere on the
 * site that wants the till as a shopkeeper actually meets it.
 */

/** Viewport 1280×820 at 2x, straight from `scripts/shots.mjs`. */
const SHOT = {
  src: "/shots/dashboard-dark.png",
  width: 2560,
  height: 1640,
};

export function DashboardShot() {
  return (
    <Tilt max={4} className="relative" spotlight={false}>
      {/* Bloom behind the window, so it reads as lit rather than pasted on. */}
      <div
        aria-hidden
        className="glow inset-x-8 -bottom-10 top-16 bg-iris-600/20 blur-[80px]"
      />

      <div className="panel rim relative overflow-hidden rounded-[20px] shadow-[0_50px_120px_-50px_rgb(4_4_10/0.95)] sm:rounded-[26px]">
        <Image
          src={SHOT.src}
          width={SHOT.width}
          height={SHOT.height}
          // The hero is the largest paint on the page; it should not wait for
          // the lazy-loading observer to decide it is visible.
          priority
          sizes="(min-width: 1024px) 980px, 100vw"
          className="block h-auto w-full"
          alt="The Flo dashboard: sales, profit, cost of goods and margin for the last seven days, with a sales-and-profit chart, the split by category, top sellers and the most recent receipts."
        />
      </div>
    </Tilt>
  );
}
